version: "3.6"
services:
    database:
      image: original/oracledb:21.3.0xe
      ports:
        - 1521:1521
        - 5500:5500
      environment:
        - ORACLE_PWD=qwe123
      volumes:
        - ./database/:/opt/oracle/oradata
    server: 
      image: original/empapp-server:1.0
      build:
        context: ./server
      ports:
        - 3000:3000
    client:
      image: nginx:1.23.1
      volumes:
        - ./client/dist/:/usr/share/nginx/html/
      ports:
        - 8080:80