SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

--
-- Create table "EMPAPP"."ROLES"
--
CREATE TABLE EMPAPP.ROLES (
  ID   NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  NAME VARCHAR2(50 BYTE),
  CONSTRAINT PK_ROLES_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS,
  UNIQUE (NAME) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

--
-- Create table "EMPAPP"."POSITIONS"
--
CREATE TABLE EMPAPP.POSITIONS (
  ID    NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  TITLE VARCHAR2(50 BYTE),
  CONSTRAINT PK_POSITIONS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS,
  UNIQUE (TITLE) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

--
-- Create table "EMPAPP"."USERS"
--
CREATE TABLE EMPAPP.USERS (
  ID          NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  NAME        VARCHAR2(50 BYTE),
  LOGIN       VARCHAR2(50 BYTE),
  PASSWORD    VARCHAR2(50 BYTE),
  ROLE_ID     NUMBER(10, 0),
  POSITION_ID NUMBER(10, 0),
  CREATEDAT   NUMBER(10, 0),
  UPDATEDAT   NUMBER(10, 0),
  LASTLOGINAT NUMBER(10, 0),
  CONSTRAINT PK_USERS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS,
  UNIQUE (LOGIN) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_USERS_POSITION_ID ON EMPAPP.USERS (POSITION_ID)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_USERS_ROLE_ID ON EMPAPP.USERS (ROLE_ID)
TABLESPACE USERS
LOGGING;

--
-- Create foreign key "FK_USERS_POSITION_ID" on table "EMPAPP"."USERS"
--
ALTER TABLE EMPAPP.USERS
ADD CONSTRAINT FK_USERS_POSITION_ID FOREIGN KEY (POSITION_ID)
REFERENCES EMPAPP.POSITIONS (ID);

--
-- Create foreign key "FK_USERS_ROLE_ID" on table "EMPAPP"."USERS"
--
ALTER TABLE EMPAPP.USERS
ADD CONSTRAINT FK_USERS_ROLE_ID FOREIGN KEY (ROLE_ID)
REFERENCES EMPAPP.ROLES (ID);

--
-- Create table "EMPAPP"."TESTS"
--
CREATE TABLE EMPAPP.TESTS (
  ID        NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  TITLE     VARCHAR2(50 BYTE),
  CREATEDAT NUMBER(10, 0),
  UPDATEDAT NUMBER(10, 0),
  CONSTRAINT PK_TESTS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

--
-- Create table "EMPAPP"."USERTESTS"
--
CREATE TABLE EMPAPP.USERTESTS (
  ID                  NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  TEST_ID             NUMBER(10, 0),
  USER_ID             NUMBER(10, 0),
  STARTEDAT           NUMBER(10, 0),
  FINISHEDAT          NUMBER(10, 0),
  COMPLETED_QUESTIONS NUMBER(3, 0),
  CORRECT_ANSWERS     NUMBER(3, 0),
  CONSTRAINT PK_USERTESTS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_USERTESTS_TEST_ID ON EMPAPP.USERTESTS (TEST_ID)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_USERTESTS_USER_ID ON EMPAPP.USERTESTS (USER_ID)
TABLESPACE USERS
LOGGING;

--
-- Create foreign key "FK_USERTESTS_TEST_ID" on table "EMPAPP"."USERTESTS"
--
ALTER TABLE EMPAPP.USERTESTS
ADD CONSTRAINT FK_USERTESTS_TEST_ID FOREIGN KEY (TEST_ID)
REFERENCES EMPAPP.TESTS (ID);

--
-- Create foreign key "FK_USERTESTS_USER_ID" on table "EMPAPP"."USERTESTS"
--
ALTER TABLE EMPAPP.USERTESTS
ADD CONSTRAINT FK_USERTESTS_USER_ID FOREIGN KEY (USER_ID)
REFERENCES EMPAPP.USERS (ID) ON DELETE CASCADE;

--
-- Create table "EMPAPP"."USERTEST_ANSWERS"
--
CREATE TABLE EMPAPP.USERTEST_ANSWERS (
  ID          NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  USERTEST_ID NUMBER(10, 0),
  ANSWER_ID   NUMBER(10, 0),
  QUESTION_ID NUMBER(10, 0),
  ANSWEREDAT  NUMBER(10, 0),
  CONSTRAINT PK_USERTEST_ANSWERS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_USERTEST_ANSWERS_USERTEST_ ON EMPAPP.USERTEST_ANSWERS (USERTEST_ID)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.UK_USERTEST_ANSWERS_QUESTION_I ON EMPAPP.USERTEST_ANSWERS (QUESTION_ID)
TABLESPACE USERS
LOGGING;

--
-- Create foreign key "FK_USERTEST_ANSWERS_USERTEST_I" on table "EMPAPP"."USERTEST_ANSWERS"
--
ALTER TABLE EMPAPP.USERTEST_ANSWERS
ADD CONSTRAINT FK_USERTEST_ANSWERS_USERTEST_I FOREIGN KEY (USERTEST_ID)
REFERENCES EMPAPP.USERTESTS (ID) ON DELETE CASCADE;

--
-- Create table "EMPAPP"."TEST_QUESTIONS"
--
CREATE TABLE EMPAPP.TEST_QUESTIONS (
  ID      NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  TEST_ID NUMBER(10, 0),
  BODY    VARCHAR2(255 BYTE),
  CONSTRAINT PK_TEST_QUESTIONS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_TEST_QUESTIONS_TEST_ID ON EMPAPP.TEST_QUESTIONS (TEST_ID)
TABLESPACE USERS
LOGGING;

--
-- Create foreign key "FK_TEST_QUESTIONS_TEST_ID" on table "EMPAPP"."TEST_QUESTIONS"
--
ALTER TABLE EMPAPP.TEST_QUESTIONS
ADD CONSTRAINT FK_TEST_QUESTIONS_TEST_ID FOREIGN KEY (TEST_ID)
REFERENCES EMPAPP.TESTS (ID) ON DELETE CASCADE;

--
-- Create table "EMPAPP"."TEST_QUESTION_ANSWERS"
--
CREATE TABLE EMPAPP.TEST_QUESTION_ANSWERS (
  ID          NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY (
  MAXVALUE 1000000000000000000000000000),
  QUESTION_ID NUMBER(10, 0),
  BODY        VARCHAR2(255 BYTE),
  ISCORRECT   NUMBER(1, 0),
  CONSTRAINT PK_TEST_QUESTION_ANSWERS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS
LOGGING;

CREATE INDEX EMPAPP.IDX_TEST_QUESTION_ANSWERS_QUES ON EMPAPP.TEST_QUESTION_ANSWERS (QUESTION_ID)
TABLESPACE USERS
LOGGING;

--
-- Create foreign key "FK_TEST_QUESTION_ANSWERS_QUEST" on table "EMPAPP"."TEST_QUESTION_ANSWERS"
--
ALTER TABLE EMPAPP.TEST_QUESTION_ANSWERS
ADD CONSTRAINT FK_TEST_QUESTION_ANSWERS_QUEST FOREIGN KEY (QUESTION_ID)
REFERENCES EMPAPP.TEST_QUESTIONS (ID) ON DELETE CASCADE;

COMMIT;